spring:
  application:
    name: logrove

  datasource:
    url: jdbc:mysql://3.35.209.68:3306/logrove_test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: logrove
    password: logrove
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

server:
  port: 8080