spring:
  application:
    name: logrove
  profiles:
    include: secret          # ← 추가

  datasource:
    url: jdbc:mysql://43.200.183.163:3306/logrove_test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true
    username: logrove
    # password는 secret에서 읽음

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect   # ← 이 줄 추가

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 500MB

server:
  port: 8080

jwt:
  expiration: 86400000

gemini:
  api:
    tag-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    eval-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent

storage:
  upload-dir: ./uploads
