spring:
  application:
    name: logrove

  datasource:
    url: jdbc:mysql://3.35.209.68:3306/logrove_test?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: logrove
    password: logrove

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080

jwt:
  secret: logrove-secret-key-must-be-at-least-32-bytes!!
  expiration: 86400000

gemini:
  api:
    key: AIzaSyA5cQPpbp2lNGsOSSHJ9sp82ilCCZGkK-8
    tag-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent
    eval-url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-pro:generateContent

storage:
  upload-dir: ./uploads