name: Deploy Backend to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy backend to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_KEY }}
          script: |
            cd ~/LoGrove-server

            git fetch origin
            git reset --hard origin/main

            pkill -f 'gradle-wrapper.jar bootRun' || true
            pkill -f 'GradleDaemon' || true
            pkill -f 'com.hansung.logrove.LogroveApplication' || true

            chmod +x gradlew
            nohup ./gradlew clean bootRun --no-daemon > boot.log 2>&1 &

            sleep 10
            tail -n 80 boot.log
